### ISSUE TITLE
Exception on updating user role during login

### ISSUE THREAD

**Issue by iROCKBUNNY** [Y-Lab/Y-VOD#105]
```
Exception on /auth/login [POST]
Traceback (most recent call last):
  File "/home/irockbunny/flask/y-vod/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/irockbunny/flask/y-vod/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/irockbunny/flask/y-vod/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/irockbunny/flask/y-vod/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/irockbunny/flask/y-vod/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/irockbunny/flask/y-vod/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/views/auth.py", line 110, in login
    if data.get('role') != user.role.name:
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by iROCKBUNNY** [comment]
Fixed in #106
