### ISSUE TITLE
Exception on `get_mac_address_from_ip(ip_address)`

### ISSUE THREAD

**Issue by iROCKBUNNY** [Y-Lab/Y-VOD#63]
```
Exception on /study/punch/27 [POST]
Traceback (most recent call last):
  File "/Users/sysop/Flask/Y-VOD/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/sysop/Flask/Y-VOD/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/sysop/Flask/Y-VOD/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/sysop/Flask/Y-VOD/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/sysop/Flask/Y-VOD/venv/lib/python3.7/site-packages/flask/app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "/Users/sysop/Flask/Y-VOD/venv/lib/python3.7/site-packages/flask/app.py", line 2087, in preprocess_request
    rv = func()
  File "./app/views/auth.py", line 28, in before_request
    .get('X-Forwarded-For', request.remote_addr))
  File "./app/utils.py", line 95, in get_mac_address_from_ip
    return get_mac_address(ip=ip_address).upper()
AttributeError: 'NoneType' object has no attribute 'upper'
```

**Comment by iROCKBUNNY** [comment]
Fixed in #64
